system_commands = {
    "ubuntu": {
        "restart": "sudo shutdown -r now",
        "shutdown": "sudo shutdown -h now",
        "update": "sudo apt update",
        "upgrade": "sudo apt upgrade",
        "install": "sudo apt install",
        "remove": "sudo apt remove",
        "search": "sudo apt search",
        "list": "sudo apt list",
        "disc": "df -h",
        "memory": "free -m",
        "processes": "ps aux",
        "users": "who",
        "go to sleep": "systemctl suspend",
        "hibernate": "systemctl hibernate",
        "lock": "gnome-screensaver-command -l",
        "turn it up": "pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo +10%",
        "turn it down": "pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo -10%",
        "crank it up": "pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo +50%",
        "turn it way down":  "pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo -50%",
        "disk usage": "du -sh *",
        "disk cleanup": "sudo apt-get autoclean && sudo apt-get autoremove",
        "get network status": "ifconfig",
        "open the terminal": "gnome-terminal",
        "close window": "xdotool getactivewindow windowclose",
        "take a screenshot": "gnome-screenshot",
        "open file manager": "nautilus",
        "create new folder": "mkdir new_folder",
        "create new file": "touch new_file.txt",
        "search for file": "locate filename",
        "fetch": "neofetch",
        "open a browser": "firefox",
        "open chrome": "chrome",
        "lets code": "code",
    },
    "windows": {
        "restart": "shutdown /r /t 0",
        "shutdown": "shutdown /s /t 0",
        "update": "winget install --id Microsoft.WindowsAppSDK",
        "upgrade": "winget upgrade",
        "install": "winget install",
        "remove": "winget uninstall",
        "search": "winget search",
        "list": "winget list",
        "disc": "fsutil volume diskfree C:",
        "memory": "systeminfo | find \"Total Physical Memory\"",
        "processes": "tasklist",
        "users": "query user",
        "go to sleep": "rundll32.exe powrprof.dll,SetSuspendState 0,1,0",
        "hibernate": "rundll32.exe powrprof.dll,SetSuspendState Hibernate",
        "lock": "rundll32.exe user32.dll, LockWorkStation",
        "turn it up": "nircmd.exe changesysvolume 2000",
        "turn it down": "nircmd.exe changesysvolume -2000",
        "disk usage": "dir /s | find \"File(s)\"",
        "disk cleanup": "cleanmgr /sagerun:1",
        "get network status": "ipconfig",
        "open the terminal": "start cmd",
        "close window": "taskkill /f /fi \"windowtitle eq cmd\"",
        "take a screenshot": "snippingtool /clip",
        "open file manager": "explorer",
        "create new folder": "md new_folder",
        "create new file": "type nul > new_file.txt",
        "search for file": "dir /s /b filename",
        "fetch": "winget show neofetch",
        "open browser": "start microsoft-edge:",
        "open chrome": "start chrome:",
        "lets code": "code",
    },
    "mac": {
        "restart": "sudo shutdown -r now",
        "shutdown": "sudo shutdown -h now",
        "update": "softwareupdate -l",
        "upgrade": "softwareupdate -i -a",
        "install": "brew install",
        "remove": "brew uninstall",
        "search": "brew search",
        "list": "brew list",
        "disc": "df -h",
        "memory": "top -l 1 | head -n 10 | grep PhysMem",
        "processes": "ps aux",
        "users": "who",
        "go to sleep": "pmset sleepnow",
        "hibernate": "sudo pmset hibernatemode 25",
        "lock": "pmset displaysleepnow",
        "turn it up": "osascript -e 'set volume output volume ((output volume of (get volume settings)) + 10)'",
        "turn it down": "osascript -e 'set volume output volume ((output volume of (get volume settings)) - 10)'",
        "disk usage": "du -sh *",
        "disk cleanup": "brew cleanup",
        "get network status": "ifconfig",
        "open the terminal": "open -a Terminal",
        "close window": "osascript -e 'tell app \"Terminal\" to close first window'",
        "take a screenshot": "screencapture -i",
        "open file manager": "open .",
        "create new folder": "mkdir new_folder",
        "create new file": "touch new_file.txt",
        "search for file": "mdfind filename",
        "fetch": "brew install neofetch",
        "open browser": "open -a Safari",
        "open chrome": "open -a Google\\ Chrome",
        "lets code": "code",
    }
}